/* EQUAL TO */
SELECT CUST_NAME FROM CUSTOMER
WHERE AGENT_CODE = 'A003';

/* NOT EQUAL TO */
SELECT AGENT_NAME FROM agents
WHERE COUNTRY <> 'INDIA';

/* LESS THAN */
SELECT AGENT_NAME FROM agents
WHERE COMMISSION < 14;

/* GREATER THAN */
SELECT AGENT_NAME FROM agents
WHERE COMMISSION > 14;