/* GROUP BY  */
SELECT COUNT(CUST_CODE), CUST_COUNTRY
FROM CUSTOMER
GROUP BY CUST_COUNTRY;

/* ORDER BY */
SELECT CUST_NAME, CUST_COUNTRY FROM CUSTOMER
ORDER BY CUST_COUNTRY;

/* Having */
SELECT COUNT(CUST_CODE), CUST_COUNTRY
FROM CUSTOMER
GROUP BY CUST_COUNTRY
HAVING COUNT(GRADE) > 2;

/* Between */
SELECT CUST_NAME, CUST_CODE FROM CUSTOMER
WHERE CUST_CODE BETWEEN 'C00020' AND 'C00025';